export const dummy_data = [
  {
    id: 0,
    registration: "2021-08-23",
    name: "Patrik Tao",
    email: "patriktao@gmail.com",
    birth: "1999-09-17",
    gender: "male",
    period: "12 Months",
    expiration_date: "2022-08-23",
    paid: true,
    expired: false,
  },
  {
    id: 1,
    registration: "2021-08-23",
    name: "Enkezhuola",
    email: "enkezhuola@sina.com",
    birth: "1996-05-26",
    gender: "female",
    period: "6 Months",
    expiration_date: "2022-08-23",
    paid: false,
    expired: true,
  },
  {
    id: 0,
    name: "Steele Mosley",
    birth: "2021-05-21",
    registration: "2021-11-26",
    expiration_date: "2014-01-19",
    gender: "male",
    period: "6 Months",
    email: "steelemosley@isoswitch.com",
    paid: false,
    expired: true,
  },
  {
    id: 1,
    name: "Natalie Kemp",
    birth: "2014-11-30",
    registration: "2018-02-24",
    expiration_date: "2018-05-29",
    gender: "female",
    period: "6 Months",
    email: "nataliekemp@isoswitch.com",
    paid: true,
    expired: true,
  },
  {
    id: 2,
    name: "Myra Wells",
    birth: "2021-05-28",
    registration: "2018-11-13",
    expiration_date: "2021-01-22",
    gender: "female",
    period: "6 Months",
    email: "myrawells@isoswitch.com",
    paid: true,
    expired: false,
  },
  {
    id: 3,
    name: "Michelle Osborne",
    birth: "2020-11-30",
    registration: "2014-02-13",
    expiration_date: "2020-04-24",
    gender: "female",
    period: "6 Months",
    email: "michelleosborne@isoswitch.com",
    paid: true,
    expired: true,
  },
  {
    id: 4,
    name: "Barr Hawkins",
    birth: "2016-11-05",
    registration: "2021-12-23",
    expiration_date: "2021-10-26",
    gender: "male",
    period: "6 Months",
    email: "barrhawkins@isoswitch.com",
    paid: true,
    expired: false,
  },
  {
    id: 5,
    name: "Calderon Mccarty",
    birth: "2014-03-17",
    registration: "2019-12-31",
    expiration_date: "2017-11-02",
    gender: "male",
    period: "6 Months",
    email: "calderonmccarty@isoswitch.com",
    paid: true,
    expired: true,
  },
  {
    id: 6,
    name: "Johnnie Tucker",
    birth: "2015-04-05",
    registration: "2021-09-25",
    expiration_date: "2017-11-15",
    gender: "female",
    period: "6 Months",
    email: "johnnietucker@isoswitch.com",
    paid: true,
    expired: false,
  },
];
